#!/usr/bin/env bash
# Setup rabbitmq queues & bindings
# Parameter: vm id

set -eu

create_exchange()
{
    name=android-events
    body='{"type":"direct","auto_delete":false,"durable":true,"internal":false,"arguments":{}}'
    curl -u "$SENZA_AMQP_USERNAME:$SENZA_AMQP_PASSWORD" -XPUT -H "content-type:application/json" -d"$body" "http://$SENZA_AMQP_HOSTNAME:15672/api/exchanges/%2f/$name"
}

create_queue()
{
    name=$1
    body='{"auto_delete":false,"durable":true,"arguments":{}}'
    curl -u "$SENZA_AMQP_USERNAME:$SENZA_AMQP_PASSWORD" -XPUT -H "content-type:application/json" -d"$body" "http://$SENZA_AMQP_HOSTNAME:15672/api/queues/%2f/$name"
}

bind_queue()
{
    name=$1
    key=$2
    body="{\"routing_key\":\"$key\",\"arguments\":{}}"
    curl -u "$SENZA_AMQP_USERNAME:$SENZA_AMQP_PASSWORD" -XPOST -H "content-type:application/json" -d"$body" "http://$SENZA_AMQP_HOSTNAME:15672/api/bindings/%2f/e/android-events/q/$name"
}

vm_id=$1
create_exchange

queues="android-events.$vm_id.battery android-events.$vm_id.gps android-events.$vm_id.recording android-events.$vm_id.gsm android-events.$vm_id.camera android-events.$vm_id.nfc android-events.$vm_id.sensors"
for queue in $queues
do
    create_queue "$queue"
    if [[ "$queue" = "android-events.$vm_id.sensors" ]]
    then
        bind_queue "$queue" "android-events.$vm_id.sensors.*"
    else
        bind_queue "$queue" "$queue"
    fi
done
